config/routes.rb
Cartoon::Application.routes.draw do

  resources :quences

  resources :tags

  namespace :admin do
    resources :comics do

      collection do
        post :update_all_sections
        get :enable_list
        get :disable_list
        get :search
        post :search
      end

      member do
        post :update_section_list
        post :enable
        post :disable 
        post :add_tag
        post :recommand
      end
    end
  end

  resources :books

  resources :bookcases

  resources :users do
    collection do
      post 'favorite_book'
    end
  end

  resources :sections

  resources :pages

  resources :comics do
    collection do
      post 'search'
      get 'search'
      get 'hot'
      get 'latest'
    end
  end

  match 'login' => "sessions#new", :as => :login
  match 'logining' => "sessions#create", :as => :logining, :via => [:post]
  match 'logout' => "sessions#destroy", :as => :logout, :via => [:get, :post]

  match 'signup' => 'users#new', :as => :signup

  root :to => 'welcome#index'

end

app/models/comic.rb
require File.expand_path("../../../lib/spider/spider.rb", __FILE__)

class Comic < ActiveRecord::Base
	has_many :sections, :order => 'sequence DESC'
	has_and_belongs_to_many :tags

	scope :enable, lambda { where("status = 1") }
	scope :disable, lambda { where("status = 0") }
	scope :hot, lambda { where("status = 1 AND hot >= 5").order('hot DESC') }
	scope :latest, lambda { where("status = 1").order("updated_at DESC") }
	scope :enable_end, lambda { where("status = 1 AND nature = 1")}
	scope :enable_continue, lambda { where("status = 1 AND nature = 0")}
	scope :search_by_name_like, lambda {|name| where("status = 1 AND name like ?", "%#{name}%")}
	scope :search_by_tag_name, lambda {|name| joins(:tags).where("status = 1 AND tags.name like ?", "%#{name}%") }


	def enable?
		status == 1 ? true : false
	end

	def enable
		update_attribute(:status, 1)
	end

	def disable
		update_attribute(:status, 0)
	end

	def run_update
		update_attribute(:update_status, 1)
	end

	def stop_update
		update_attribute(:update_status, 0)
	end

	def updating?
		case update_status
			when 0 : false
			when 1 : true
		end
	end

	def update_section_list
		Thread.new {
			Spider::Imanhua.new.update_comic(self)
		}
	end

	def cover_path
		"/covers/#{id}.jpg"
	end

	def nature_explain
		case nature
		when 1 : '已完结'
		when 0 : '连载中'
		end
	end

	def latest_section
		Section.where(:comic_id => self.id).order('sequence DESC').limit(1).first
	end

	def push_in_recommand_quence
		Quence.create(:comic_id => id)
	end

	

	class << self

		def get_by_sid sid
			where("url like ?", "%/#{sid}/%").limit(1).first
		end

		def update_all_sections
			Thread.new {
				enable_continue.each do |comic|
					Spider::Imanhua.new.update_comic comic
				end
			}
		end

		def today
		    where("created_at > #{(Time.now - 1.day)}").order('created_at DESC')
		end

		def recommand
			s = Quence.order("created_at DESC").limit(1).first
			s.nil? ? nil : s.comic
		end

	end
end

app/controllers/admin/comics_controller.rb
class Admin::ComicsController < Admin::ApplicationController

	before_filter :find_model

  def index
  	@comics = Comic.paginate(:per_page => 50, :page => params[:page]).order('status DESC')
  end

  def show
  end

  def enable
  	@comic.enable
  	redirect_to :back
  end

  def disable
  	@comic.disable
  	redirect_to :back
  end

  def enable_list
  	@comics = Comic.enable.paginate(:per_page => 10, :page => params[:page]).order('status DESC')
  end

  def disable_list
  	@comics = Comic.disable.paginate(:per_page => 50, :page => params[:page]).order('status DESC')
  end

  def update
  	@comic.update_attributes(params[:comic])
  	redirect_to :back
  end

  def update_hot
  	@comic.update_attribute(:hot, params[:comic])
  	render :json => {:status => 'succes'}
  end

  def update_section_list
    @comic.update_section_list
    redirect_to :back
  end

  def update_all_sections
    Comic.update_all_sections
    redirect_to :back
  end

  def add_tag
    @comic.tags.clear
    params[:tags].split(' ').each do |t|
      tag = Tag.find_by_name(t)
      unless tag
        tag = Tag.create(:name => t)
      end
      unless @comic.tags.include?(tag)
        @comic.tags << tag
      end
    end
    redirect_to :back
  end

  def recommand
    @comic.push_in_recommand_quence
    redirect_to :back
  end

  def search
    @comics = Comic.where("name like ?", "%#{params[:key]}%").paginate(:per_page => 20, :page => params[:page])
  end

  private

  def find_model
  	@comic = Comic.find(params[:id]) if params[:id]
  end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController

  before_filter :find_comic

  def show
  end
 

  def search
    @comics1 = Comic.search_by_name_like(params[:key])
    @comic2 = Comic.search_by_tag_name(params[:key])
    @comics = (@comics1 | @comic2).paginate(:page => params[:page], :per_page => 20)
  end

  def hot
    @comics = Comic.hot.paginate(:per_page => 20, :page => params[:page])
  end

  def latest
    @comics = Comic.latest.limit(100).paginate(:per_page => 20, :page => params[:page])
  end



  private

  def find_comic
    @comic = Comic.find(params[:id]) if params[:id]
  end

end

app/helpers/admin/comics_helper.rb
module Admin::ComicsHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/views/comics/_form.html.erb
<%= form_for(@comic) do |f| %>
  <% if @comic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comic.errors.count, "error") %> prohibited this comic from being saved:</h2>

      <ul>
      <% @comic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :cover %><br />
    <%= f.text_field :cover %>
  </div>
  <div class="field">
    <%= f.label :pages %><br />
    <%= f.text_field :pages %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comics/_list.html.erb
<%= content_for :head do  %>
	<%= stylesheet_link_tag 'comics' %>
<% end -%>
<div class='row'>

	<div class='span8 well'>
		<ul class='unstyled'>
			<% @comics.each do |comic| %>
			<li class='comic'>
				<div class='row'>
					<div class='cover span2'>
						<%= link_to comic do %>
							<%= image_tag comic.cover_path %>
						<% end -%>
					</div>

					<div class='info span6' style='margin-left: 0'>
						<div class='name'>
							<%= link_to comic.name, comic %>
						</div>
						<div class='intro'>
							<p>
								<% if comic.description %>
									<%= comic.description.truncate(200) %>
								<% end -%>
							</p>
						</div>

						<div class='tags'>
							<% comic.tags.each do |tag| %>
							<span>
								<%= link_to tag.name, search_comics_path(:key => tag.name) %>
							</span>
							<% end -%>
						</div>

					</div>
				</div>
				<hr class='split'>
			</li>
			<% end -%>
		</ul>
		<%= will_paginate @comics, :previous_label => '<', :next_label => '>' %>
	</div>



</div>

app/views/comics/edit.html.erb
<h1>Editing comic</h1>

<%= render 'form' %>

<%= link_to 'Show', @comic %> |
<%= link_to 'Back', comics_path %>

app/views/comics/hot.html.erb
<%= content_for :head do %>
	<title>月蚀漫画 - 最热漫画</title>
<% end -%>

<%= render :partial => 'list' %>

app/views/comics/index.html.erb
<h1>Listing comics</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Cover</th>
    <th>Pages</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comics.each do |comic| %>
  <tr>
    <td><%= comic.name %></td>
    <td><%= comic.description %></td>
    <td><%= comic.cover %></td>
    <td><%= comic.pages %></td>
    <td><%= link_to 'Show', comic %></td>
    <td><%= link_to 'Edit', edit_comic_path(comic) %></td>
    <td><%= link_to 'Destroy', comic, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comic', new_comic_path %>

app/views/comics/latest.html.erb
<%= content_for :head do %>

	<title>月蚀漫画 - 最新更新的漫画</title>

	<style type="text/css">

		.name {
			font-size: 18px;
			margin: 15px 0;
		}

		.time {
			color: green;
			font-size: 18px;
		}

		.time a { 
			color: green;
			margin: 5px;
		}

		.comic:nth-child(odd) {
			background-color: #EEE;
		}

		.info {
			margin: 15px 0;
		}

		.comic {
			margin: 5px;
		}
	</style>
<% end -%>


<div class='row'>

	<div class='span8 well'>
		<ul class='nav nav-pills nav-stacked'>
			<% @comics.each do |comic| %>
			<% section = comic.sections.first %>
			<% next if section.nil? %>
			<li style='' class='comic'>
				<div class='content row'>
					<div class='cover span1'>
						<%= link_to section do %>
							<%= image_tag comic.cover_path, :height => '80px' %>
						<% end -%>
					</div>
					<div class='info span6'>
						<div class='row'>
							<div class='span3'>

						<%= link_to section, :class => 'name' do  %>
							<%= comic.name %>
							<span class='section-name'>(<%= section.name %>)</span>

							<% end -%>
							</div>
							<div class='span2 offset1'>
						<span class='time'> <%= link_to timeformat(comic.updated_at), section %></span>
						</div>
						</div>
					</div>
					
				</div>
			</li>
			<% end -%>
		</ul>
		<%= will_paginate @comics, :previous_label => '<', :next_label => '>' %>
	</div>

</div>

app/views/comics/new.html.erb
<h1>New comic</h1>

<%= render 'form' %>

<%= link_to 'Back', comics_path %>

app/views/comics/search.html.erb
<%= content_for :head do %>

	<title>月蚀漫画 - <%= "搜索 '#{params[:key]}'" %></title>

<% end -%>

<div class='row'>
	<div class='span8'>
	 <%= form_tag search_comics_path, :class => 'form-search' do %>
	     <%= text_field_tag :key , params[:key],:class => 'input-long search-query', :style => 'height:30px' %>
	  <button type="submit" class="btn" style='height: 40px;margin:10px 5px'>搜索</button>
	   <% end -%>
	</div>
</div>

<div class='row'>
	<div class='span8' style='margin: 0 0 20px 35px'>
		<% Tag.limit(20).each do |t| %>
		    <%= link_to t.name, search_comics_path(:key => t.name) %>
		<% end -%>
	</div>
</div>

<%= render :partial => 'list' %>

app/views/comics/show.html.erb
<%= content_for :head do %>
	
	<title>月蚀漫画 - <%= @comic.name %></title>

	<script type="text/javascript">

		$(function () {
			$('.nav-stacked li').hover(function () {
				$(this).addClass('active');
			}, function () {
				$(this).removeClass('active');
			})
		})
		
	</script>

	<style type="text/css">

		.nav {
			font-size: 18px;
		}

		.nav-pills > .active li > a:hover {
			color: white;
			background-color: #08C;
		} 
	</style>
<% end -%>

<ul class="breadcrumb">
  <li>
    <a href="/">首页</a> <span class="divider">/</span>
  </li>
  <li class="active"><%= @comic.name %></li>
</ul>
<div class='row-fluid'>

<div class='span3'>
	<div class='well sidebar-nav'>
		<ul class='nav nav-pills nav-stacked'>
			<% @comic.sections.each do |s| %>
				<% unless s.pages.blank? %>
					<li>
						<%= link_to s.name, s %>
					</li>
				<% end -%>
			<% end -%>
		</ul>
</div>

</div>


<div class='span9'>
	<div>
	<h1  style='padding-bottom: 15px'><%= @comic.name %></h1>
	<div>
		<%= image_tag @comic.cover_path, :style => 'float: left' %>
		<div style='float: left;padding: 15px'>
			<% if login? && current_user.comics.include?(@comic) %>
				<span style='background-color:#F7F7F7;padding:5px;color:green;font-size:18px;border:1px solid silver'>已收藏</span>
			<% else %>
			<%= form_tag favorite_book_users_path do %>
				<%= hidden_field_tag :comic_id, @comic.id %>
				<button class="btn btn-success">放入书柜</button>
			<% end -%>
			<% end -%>

			<div  style='margin:15px 0 0;padding: 5px'>
				状态: <%= @comic.nature_explain %>
			</div>

			<div style='margin:5px 0;padding: 5px'>
				更新日期: <%= @comic.updated_at.strftime("%y/%m/%d") %>
			</div>
		</div>
	</div>


	<div  style='clear:both;padding: 15px 0'>

	<h3 class='title'>简介:</h3>
	<p style='clear:both;padding: 15px'>
		<%= @comic.description %>
	   </p>
	</div>


	</div>

	<div  style='clear:both;padding: 15px 0'>

	<h3 class='title'>标签:</h3>
		<div style='font-size:18px;margin:15px'>
			<% @comic.tags.each do |tag| %>
				<span>
					<%= link_to tag.name, search_comics_path(:key => tag.name) %>
				</span>
			<% end -%>
		</div>
	</div>


	</div>
	<!-- <div style='clear:both;margin:20px 0'>
		<h3><%= link_to "> 美图", '#' %></h3>
		<ul class="thumbnails">
		  <% (1..8).each do %>
		  	<li>
		  	  <div class="thumbnail">
		  	  	<a href="#">
		  	    <img src="http://placehold.it/160x200" alt="">
		  	    </a>
		  	  </div>
		  	</li>
		  <% end -%>
		  
		</ul>
	</div> -->
</div>
</div>