config/routes.rb
Cartoon::Application.routes.draw do

  resources :quences

  resources :tags

  namespace :admin do
    resources :comics do

      collection do
        post :update_all_sections
        get :enable_list
        get :disable_list
        get :search
        post :search
      end

      member do
        post :update_section_list
        post :enable
        post :disable 
        post :add_tag
        post :recommand
      end
    end
  end

  resources :books

  resources :bookcases

  resources :users do
    collection do
      post 'favorite_book'
    end
  end

  resources :sections

  resources :pages

  resources :comics do
    collection do
      post 'search'
      get 'search'
      get 'hot'
      get 'latest'
    end
  end

  match 'login' => "sessions#new", :as => :login
  match 'logining' => "sessions#create", :as => :logining, :via => [:post]
  match 'logout' => "sessions#destroy", :as => :logout, :via => [:get, :post]

  match 'signup' => 'users#new', :as => :signup

  root :to => 'welcome#index'

end

app/models/book.rb
class Book < ActiveRecord::Base

	belongs_to :bookcase

	belongs_to :comic

end

app/models/bookcase.rb
class Bookcase < ActiveRecord::Base
	belongs_to :user
	has_many :books
end

app/models/comic.rb
require File.expand_path("../../../lib/spider/spider.rb", __FILE__)

class Comic < ActiveRecord::Base
	has_many :sections, :order => 'sequence DESC'
	has_and_belongs_to_many :tags

	scope :enable, lambda { where("status = 1") }
	scope :disable, lambda { where("status = 0") }
	scope :hot, lambda { where("status = 1 AND hot >= 5").order('hot DESC') }
	scope :latest, lambda { where("status = 1").order("updated_at DESC") }
	scope :enable_end, lambda { where("status = 1 AND nature = 1")}
	scope :enable_continue, lambda { where("status = 1 AND nature = 0")}
	scope :search_by_name_like, lambda {|name| where("status = 1 AND name like ?", "%#{name}%")}
	scope :search_by_tag_name, lambda {|name| joins(:tags).where("status = 1 AND tags.name like ?", "%#{name}%") }


	def enable?
		status == 1 ? true : false
	end

	def enable
		update_attribute(:status, 1)
	end

	def disable
		update_attribute(:status, 0)
	end

	def run_update
		update_attribute(:update_status, 1)
	end

	def stop_update
		update_attribute(:update_status, 0)
	end

	def updating?
		case update_status
			when 0 : false
			when 1 : true
		end
	end

	def update_section_list
		Thread.new {
			Spider::Imanhua.new.update_comic(self)
		}
	end

	def cover_path
		"/covers/#{id}.jpg"
	end

	def nature_explain
		case nature
		when 1 : '已完结'
		when 0 : '连载中'
		end
	end

	def latest_section
		Section.where(:comic_id => self.id).order('sequence DESC').limit(1).first
	end

	def push_in_recommand_quence
		Quence.create(:comic_id => id)
	end

	

	class << self

		def get_by_sid sid
			where("url like ?", "%/#{sid}/%").limit(1).first
		end

		def update_all_sections
			Thread.new {
				enable_continue.each do |comic|
					Spider::Imanhua.new.update_comic comic
				end
			}
		end

		def today
		    where("created_at > #{(Time.now - 1.day)}").order('created_at DESC')
		end

		def recommand
			s = Quence.order("created_at DESC").limit(1).first
			s.nil? ? nil : s.comic
		end

	end
end

app/models/page.rb
class Page < ActiveRecord::Base
	belongs_to :section

	def comic
		section.comic
	end

	def path
		root = '/home/www/images/comics'
		comic_dir = "#{root}/#{self.section.comic.id}"
		section_dir = "#{comic_dir}/#{section.id}"
		Dir.mkdir(root)  unless File.exist?(root)
		Dir.mkdir(comic_dir)  unless File.exist?(comic_dir)
		Dir.mkdir(section_dir)  unless File.exist?(section_dir)
		"#{section_dir}/#{self.sequence}.jpg"
	end

	def image_path
		"/cp/#{section.comic.id}/#{section.id}/#{sequence}.jpg"
	end

	def image_path_on_disk
		"/home/www/images/comics/#{section.comic.id}/#{section.id}/#{sequence}.jpg"
	end

	def next
		next_page = Page.where("section_id = #{section.id} AND sequence = #{sequence + 1}").limit(1).first
		return unless next_page
		if  File.exist?(next_page.image_path_on_disk)
			return next_page 
		else
			return next_page.next
		end
	end

	def prev
		prev_page = Page.where("section_id = #{section.id} AND sequence = #{sequence - 1}").limit(1).first
	end
end

app/models/quence.rb
class Quence < ActiveRecord::Base
	belongs_to :comic
end

app/models/section.rb
require File.expand_path("../../../lib/spider/spider.rb", __FILE__)

class Section < ActiveRecord::Base
	belongs_to :comic

	has_many :pages

	after_create do |section|
		section.comic.update_attribute(:updated_at, Time.now)
	end

	def first_page
		page = pages.first
		return unless page
		if File.exist? page.image_path_on_disk
			return page
		else
			return page.next
		end
	end


	def next
		next_section = Section.where(:comic_id => comic.id, :sequence => sequence + 1).limit(1).first
		if next_section && next_section.pages.blank?
			return nil
		end
		next_section
	end

	def update_pages
		Spider::Imanhua.new.update_section self
	end



	class << self

		def today
			 where("created_at >= '#{(Time.now.strftime("%Y-%m-%d"))}'").order('created_at DESC')
		end

		def yesterday
			where("created_at >= '#{((Time.now - 1.day).strftime("%Y-%m-%d"))}'").order('created_at DESC')
		end
	end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :comics
end

app/models/user.rb
class User < ActiveRecord::Base

	validates :email, :presence => {:message => "邮箱不能为空"}, 
					  :uniqueness => {:message => '此邮箱已经存在'},
					  :format => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :message => "邮箱格式错误"}
	validates :name,
					 :length => { :in => 4..15, :message => "昵称长度为4到15位" }	
	validates :password,
						 :length => { :in => 6..15, :message => "密码长度为6到15位" }	

	has_one :bookcase, :dependent => :destroy
	has_many :books, :through => :bookcase
	has_many :comics, :through => :books




	after_create do |user|
		Bookcase.create(:user_id => user.id)
	end

	def add_comic_to_bookcase comic
		return if Book.find_by_comic_id_and_bookcase_id(comic.id, bookcase.id)
		Book.create(:comic_id => comic.id, :bookcase_id => bookcase.id)
	end

	def comics_order_by_update_section_time
		comics.sort do |a, b|
			b.sections.first.created_at <=> a.sections.first.created_at
 		end
	end

	class << self

		def authenticate email, password
		   find_by_email_and_password(email, password)
		end

	end

	

end

app/controllers/admin/welcome_controller.rb
class Admin::WelcomeController < Admin::ApplicationController
  def index
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@hot = Comic.hot.limit(8)
  	@latest = Comic.latest.limit(8)
  	@recommand = Comic.recommand
  end

  def latest
  end

  def hot
  end
  
end

app/helpers/admin/welcome_helper.rb
module Admin::WelcomeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	FORMAT_TIME = "%y/%m/%d"
	FORMAT_TIME_MD = "%m月%d日"

	def is_active? options
		"active" if params[:controller] == options[:controller] && params[:action] == options[:action]
	end

	def current_user
		User.find(session[:user_id]) if login?
	end

	def login?
		session[:user_id] ? true : false
	end

	def timeformat time
		s = time.strftime(FORMAT_TIME)
		if s == Time.now.strftime(FORMAT_TIME)
			return '今天'
		end

		if s == Time.now.yesterday.strftime(FORMAT_TIME)
			return "昨天"
		end
		time.strftime(FORMAT_TIME_MD)
	end
	
end

app/helpers/bookcases_helper.rb
module BookcasesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quences_helper.rb
module QuencesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/welcome/index.html.erb
<h1>Admin::Welcome#index</h1>
<p>Find me in app/views/admin/welcome/index.html.erb</p>

app/views/welcome/_thumbs.html.erb
<%= content_for :head do %>
  <style type="text/css">
  </style>
  
<% end -%>


<ul class="thumbnails" style='padding:15px'>
  <% comics.each do |comic| %>
    <li class="span2">
      <div class="thumbnail">
        <%= link_to comic do %>
            <%= image_tag comic.cover_path %>
        <!-- <img src="http://placehold.it/160x200" alt=""> -->
        <% end -%>
        </a>
        <h3 class='comic_name' style=''>
           <%= link_to comic.name.truncate(7), comic %>
         </h3>
         <div class='tags' style='height: 20px'>
           <% comic.tags[0..2].each do |t| %>
           <span>
             <%= link_to t.name, search_comics_path(:key => t.name) %>
             </span> 
           <% end -%>
        </div>
      </div>
    </li>
  <% end -%>
  
</ul>

app/views/welcome/index.html.erb
	<%= content_for :head do %>

    <title>月蚀漫画 - 专注于精品漫画</title>

    <style type="text/css">
      .thumbnail{
        border: none;
      }

      .image-box {
        display: block;
        box-shadow: 10px 10px 5px #888888;
      }

  /*    .recommand .cover{
        width: 150px;
        float: left;
      }

      .recommand .info {
        width: 400px;
        float: left;
      }*/

      .recommand .name {
        font-size: 24px;
        margin: 15px 0;
      }

      .recommand .intro {
        padding: 15px;
      }
    </style>
  <% end -%>
      

    
      <div class="row">
        <%= render :partial => 'share/sidebar' %>
        
        <div class="span9">



          <% if @recommand %>
            <div class='well recommand' style=''>
              <h2 style='color:red'>本周推荐</h2>
              <hr style='border-color: silver'/>

              <div class='row'>
                <div class='cover span2'>
                  <%= link_to @recommand do %>
                    <%= image_tag @recommand.cover_path %>
                  <% end -%>
                </div>

                <div class='info span6' style='margin-left: 0'>
                  <div class='name'>
                    <%= link_to @recommand.name, @recommand %>
                  </div>
                  <div class='intro'>
                    <p>
                      <% if @recommand.description %>
                        <%= @recommand.description.truncate(200) %>
                      <% end -%>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          <% end -%>

          <div class='well' style='clear:both'>
            <h2><%= link_to '> 最近更新', latest_comics_path %></h2>
            <hr style='border-color: silver'/>
              <%= render :partial => 'thumbs', :locals => {:comics => @latest} %>
          </div>

          <div class='well'>
            <h2><%= link_to '> 热门', hot_comics_path %></h2>
            <hr style='border-color: silver'/>
              <%= render :partial => 'thumbs', :locals => {:comics => @hot} %>
          </div>
          	
        </div>
        
      </div>  

     

   