config/routes.rb
Cartoon::Application.routes.draw do

  resources :quences

  resources :tags

  namespace :admin do
    resources :comics do

      collection do
        post :update_all_sections
        get :enable_list
        get :disable_list
        get :search
        post :search
      end

      member do
        post :update_section_list
        post :enable
        post :disable 
        post :add_tag
        post :recommand
      end
    end
  end

  resources :books

  resources :bookcases

  resources :users do
    collection do
      post 'favorite_book'
    end
  end

  resources :sections

  resources :pages

  resources :comics do
    collection do
      post 'search'
      get 'search'
      get 'hot'
      get 'latest'
    end
  end

  match 'login' => "sessions#new", :as => :login
  match 'logining' => "sessions#create", :as => :logining, :via => [:post]
  match 'logout' => "sessions#destroy", :as => :logout, :via => [:get, :post]

  match 'signup' => 'users#new', :as => :signup

  root :to => 'welcome#index'

end

app/models/book.rb
class Book < ActiveRecord::Base

	belongs_to :bookcase

	belongs_to :comic

end

app/models/bookcase.rb
class Bookcase < ActiveRecord::Base
	belongs_to :user
	has_many :books
end

app/models/comic.rb
require File.expand_path("../../../lib/spider/spider.rb", __FILE__)

class Comic < ActiveRecord::Base
	has_many :sections, :order => 'sequence DESC'
	has_and_belongs_to_many :tags

	scope :enable, lambda { where("status = 1") }
	scope :disable, lambda { where("status = 0") }
	scope :hot, lambda { where("status = 1 AND hot >= 5").order('hot DESC') }
	scope :latest, lambda { where("status = 1").order("updated_at DESC") }
	scope :enable_end, lambda { where("status = 1 AND nature = 1")}
	scope :enable_continue, lambda { where("status = 1 AND nature = 0")}
	scope :search_by_name_like, lambda {|name| where("status = 1 AND name like ?", "%#{name}%")}
	scope :search_by_tag_name, lambda {|name| joins(:tags).where("status = 1 AND tags.name like ?", "%#{name}%") }


	def enable?
		status == 1 ? true : false
	end

	def enable
		update_attribute(:status, 1)
	end

	def disable
		update_attribute(:status, 0)
	end

	def run_update
		update_attribute(:update_status, 1)
	end

	def stop_update
		update_attribute(:update_status, 0)
	end

	def updating?
		case update_status
			when 0 : false
			when 1 : true
		end
	end

	def update_section_list
		Thread.new {
			Spider::Imanhua.new.update_comic(self)
		}
	end

	def cover_path
		"/covers/#{id}.jpg"
	end

	def nature_explain
		case nature
		when 1 : '已完结'
		when 0 : '连载中'
		end
	end

	def latest_section
		Section.where(:comic_id => self.id).order('sequence DESC').limit(1).first
	end

	def push_in_recommand_quence
		Quence.create(:comic_id => id)
	end

	

	class << self

		def get_by_sid sid
			where("url like ?", "%/#{sid}/%").limit(1).first
		end

		def update_all_sections
			Thread.new {
				enable_continue.each do |comic|
					Spider::Imanhua.new.update_comic comic
				end
			}
		end

		def today
		    where("created_at > #{(Time.now - 1.day)}").order('created_at DESC')
		end

		def recommand
			s = Quence.order("created_at DESC").limit(1).first
			s.nil? ? nil : s.comic
		end

	end
end

app/models/page.rb
class Page < ActiveRecord::Base
	belongs_to :section

	def comic
		section.comic
	end

	def path
		root = '/home/www/images/comics'
		comic_dir = "#{root}/#{self.section.comic.id}"
		section_dir = "#{comic_dir}/#{section.id}"
		Dir.mkdir(root)  unless File.exist?(root)
		Dir.mkdir(comic_dir)  unless File.exist?(comic_dir)
		Dir.mkdir(section_dir)  unless File.exist?(section_dir)
		"#{section_dir}/#{self.sequence}.jpg"
	end

	def image_path
		"/cp/#{section.comic.id}/#{section.id}/#{sequence}.jpg"
	end

	def image_path_on_disk
		"/home/www/images/comics/#{section.comic.id}/#{section.id}/#{sequence}.jpg"
	end

	def next
		next_page = Page.where("section_id = #{section.id} AND sequence = #{sequence + 1}").limit(1).first
		return unless next_page
		if  File.exist?(next_page.image_path_on_disk)
			return next_page 
		else
			return next_page.next
		end
	end

	def prev
		prev_page = Page.where("section_id = #{section.id} AND sequence = #{sequence - 1}").limit(1).first
	end
end

app/models/quence.rb
class Quence < ActiveRecord::Base
	belongs_to :comic
end

app/models/section.rb
require File.expand_path("../../../lib/spider/spider.rb", __FILE__)

class Section < ActiveRecord::Base
	belongs_to :comic

	has_many :pages

	after_create do |section|
		section.comic.update_attribute(:updated_at, Time.now)
	end

	def first_page
		page = pages.first
		return unless page
		if File.exist? page.image_path_on_disk
			return page
		else
			return page.next
		end
	end


	def next
		next_section = Section.where(:comic_id => comic.id, :sequence => sequence + 1).limit(1).first
		if next_section && next_section.pages.blank?
			return nil
		end
		next_section
	end

	def update_pages
		Spider::Imanhua.new.update_section self
	end



	class << self

		def today
			 where("created_at >= '#{(Time.now.strftime("%Y-%m-%d"))}'").order('created_at DESC')
		end

		def yesterday
			where("created_at >= '#{((Time.now - 1.day).strftime("%Y-%m-%d"))}'").order('created_at DESC')
		end
	end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :comics
end

app/models/user.rb
class User < ActiveRecord::Base

	validates :email, :presence => {:message => "邮箱不能为空"}, 
					  :uniqueness => {:message => '此邮箱已经存在'},
					  :format => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :message => "邮箱格式错误"}
	validates :name,
					 :length => { :in => 4..15, :message => "昵称长度为4到15位" }	
	validates :password,
						 :length => { :in => 6..15, :message => "密码长度为6到15位" }	

	has_one :bookcase, :dependent => :destroy
	has_many :books, :through => :bookcase
	has_many :comics, :through => :books




	after_create do |user|
		Bookcase.create(:user_id => user.id)
	end

	def add_comic_to_bookcase comic
		return if Book.find_by_comic_id_and_bookcase_id(comic.id, bookcase.id)
		Book.create(:comic_id => comic.id, :bookcase_id => bookcase.id)
	end

	def comics_order_by_update_section_time
		comics.sort do |a, b|
			b.sections.first.created_at <=> a.sections.first.created_at
 		end
	end

	class << self

		def authenticate email, password
		   find_by_email_and_password(email, password)
		end

	end

	

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :find_user
  before_filter :require_login, :only => [:favorite_book]

  def show
    @user = User.find(params[:id])
    @comics = @user.comics_order_by_update_section_time
  end

  def new
    @user = User.new
  end


  def create
    @user = User.new(params[:user])
      if @user.save
        login @user
        redirect_to root_path
      else
        render :action => "new"
      end
  end

  def favorite_book
    @comic = Comic.find(params[:comic_id])
    current_user.add_comic_to_bookcase @comic
    redirect_to :back
  end

  private

  def find_user
    @user = User.find(params[:id]) if params[:id]
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

	FORMAT_TIME = "%y/%m/%d"
	FORMAT_TIME_MD = "%m月%d日"

	def is_active? options
		"active" if params[:controller] == options[:controller] && params[:action] == options[:action]
	end

	def current_user
		User.find(session[:user_id]) if login?
	end

	def login?
		session[:user_id] ? true : false
	end

	def timeformat time
		s = time.strftime(FORMAT_TIME)
		if s == Time.now.strftime(FORMAT_TIME)
			return '今天'
		end

		if s == Time.now.yesterday.strftime(FORMAT_TIME)
			return "昨天"
		end
		time.strftime(FORMAT_TIME_MD)
	end
	
end

app/helpers/bookcases_helper.rb
module BookcasesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quences_helper.rb
module QuencesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= tag.name %></td>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tag.name %>
</p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :sex %><br />
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Password</th>
    <th>Sex</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.password %></td>
    <td><%= user.sex %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= content_for :head do %>
  <title>月蚀漫画 - 注册</title>
<% end -%>



<%= form_for(@user, :html => {:class => 'form-horizontal'}) do |f| %>
  <fieldset>
    <legend>注册</legend>
    <div class="control-group <%=  "error" unless @user.errors[:email].blank? %>">
    	<%= f.label :email, "邮箱", :class => 'control-label' %>
      <div class="controls">
      	<%= f.text_field :email, :class => 'input-xlarge' %>
        <p class="help-block"><%= @user.errors[:email] %></p>
      </div>
    </div>

    <div class="control-group <%=  "error" unless @user.errors[:name].blank? %>">
    	<%= f.label :name, "昵称", :class => 'control-label' %>
      <div class="controls">
      	<%= f.text_field :name, :class => 'input-xlarge' %>
        <p class="help-block"><%= @user.errors[:name] %></p>
      </div>
    </div>

    <div class="control-group <%=  "error" unless @user.errors[:password].blank? %>">
    	<%= f.label :password, "密码", :class => 'control-label' %>
      <div class="controls">
      	<%= f.password_field :password, :class => 'input-xlarge' %>
        <p class="help-block"><%= @user.errors[:password] %></p>
      </div>
    </div>

    <div class="form-actions">
        <button type="submit" class="btn btn-success">注册</button>
    </div>

  </fieldset>
<% end -%>

app/views/users/show.html.erb
<%= content_for :head do %>
  
  <title>月蚀漫画 - 个人书架</title>

  <style type="text/css">

  </style>
  
<% end -%>

<div class="row">
  
  
  <div class="span9">
    
    <div class='well'>
      <h2 class='title'>书架</h2>
      <hr style='border-color: silver'/>
      <% if @comics.blank? %>
        <p style='font-size: 24px;text-align:center'>
           还没有收藏漫画
        </p>
      <% else %>
        <ul class="thumbnails" style='padding:15px'>
          <% @comics.each do |comic| %>
            <li class="span2" style='width: 125px'>
              <div class="thumbnail">
                <%= link_to comic do %>
                    <%= image_tag comic.cover_path %>
                <!-- <img src="http://placehold.it/160x200" alt=""> -->
                <% end -%>
                </a>
                <h3 class='comic_name'>
                   <%= link_to comic.name.truncate(7), comic %>
                </h3>
                 <div style='padding:2px'>
                  <%= link_to comic.sections.first.name, comic.sections.first, :style => 'color:#FA8258' %>
                 </div>
              </div>
            </li>
          <% end -%>
          
        </ul>
        <% end -%>
    </div>
    	
  </div>