config/routes.rb
Cartoon::Application.routes.draw do

  resources :quences

  resources :tags

  namespace :admin do
    resources :comics do

      collection do
        post :update_all_sections
        get :enable_list
        get :disable_list
        get :search
        post :search
      end

      member do
        post :update_section_list
        post :enable
        post :disable 
        post :add_tag
        post :recommand
      end
    end
  end

  resources :books

  resources :bookcases

  resources :users do
    collection do
      post 'favorite_book'
    end
  end

  resources :sections

  resources :pages

  resources :comics do
    collection do
      post 'search'
      get 'search'
      get 'hot'
      get 'latest'
    end
  end

  match 'login' => "sessions#new", :as => :login
  match 'logining' => "sessions#create", :as => :logining, :via => [:post]
  match 'logout' => "sessions#destroy", :as => :logout, :via => [:get, :post]

  match 'signup' => 'users#new', :as => :signup

  root :to => 'welcome#index'

end

app/models/comic.rb
require File.expand_path("../../../lib/spider/spider.rb", __FILE__)

class Comic < ActiveRecord::Base
	has_many :sections, :order => 'sequence DESC'
	has_and_belongs_to_many :tags

	scope :enable, lambda { where("status = 1") }
	scope :disable, lambda { where("status = 0") }
	scope :hot, lambda { where("status = 1 AND hot >= 5").order('hot DESC') }
	scope :latest, lambda { where("status = 1").order("updated_at DESC") }
	scope :enable_end, lambda { where("status = 1 AND nature = 1")}
	scope :enable_continue, lambda { where("status = 1 AND nature = 0")}
	scope :search_by_name_like, lambda {|name| where("status = 1 AND name like ?", "%#{name}%")}
	scope :search_by_tag_name, lambda {|name| joins(:tags).where("status = 1 AND tags.name like ?", "%#{name}%") }


	def enable?
		status == 1 ? true : false
	end

	def enable
		update_attribute(:status, 1)
	end

	def disable
		update_attribute(:status, 0)
	end

	def run_update
		update_attribute(:update_status, 1)
	end

	def stop_update
		update_attribute(:update_status, 0)
	end

	def updating?
		case update_status
			when 0 : false
			when 1 : true
		end
	end

	def update_section_list
		Thread.new {
			Spider::Imanhua.new.update_comic(self)
		}
	end

	def cover_path
		"/covers/#{id}.jpg"
	end

	def nature_explain
		case nature
		when 1 : '已完结'
		when 0 : '连载中'
		end
	end

	def latest_section
		Section.where(:comic_id => self.id).order('sequence DESC').limit(1).first
	end

	def push_in_recommand_quence
		Quence.create(:comic_id => id)
	end

	

	class << self

		def get_by_sid sid
			where("url like ?", "%/#{sid}/%").limit(1).first
		end

		def update_all_sections
			Thread.new {
				enable_continue.each do |comic|
					Spider::Imanhua.new.update_comic comic
				end
			}
		end

		def today
		    where("created_at > #{(Time.now - 1.day)}").order('created_at DESC')
		end

		def recommand
			s = Quence.order("created_at DESC").limit(1).first
			s.nil? ? nil : s.comic
		end

	end
end

app/controllers/admin/comics_controller.rb
class Admin::ComicsController < Admin::ApplicationController

	before_filter :find_model

  def index
  	@comics = Comic.paginate(:per_page => 50, :page => params[:page]).order('status DESC')
  end

  def show
  end

  def enable
  	@comic.enable
  	redirect_to :back
  end

  def disable
  	@comic.disable
  	redirect_to :back
  end

  def enable_list
  	@comics = Comic.enable.paginate(:per_page => 10, :page => params[:page]).order('status DESC')
  end

  def disable_list
  	@comics = Comic.disable.paginate(:per_page => 50, :page => params[:page]).order('status DESC')
  end

  def update
  	@comic.update_attributes(params[:comic])
  	redirect_to :back
  end

  def update_hot
  	@comic.update_attribute(:hot, params[:comic])
  	render :json => {:status => 'succes'}
  end

  def update_section_list
    @comic.update_section_list
    redirect_to :back
  end

  def update_all_sections
    Comic.update_all_sections
    redirect_to :back
  end

  def add_tag
    @comic.tags.clear
    params[:tags].split(' ').each do |t|
      tag = Tag.find_by_name(t)
      unless tag
        tag = Tag.create(:name => t)
      end
      unless @comic.tags.include?(tag)
        @comic.tags << tag
      end
    end
    redirect_to :back
  end

  def recommand
    @comic.push_in_recommand_quence
    redirect_to :back
  end

  def search
    @comics = Comic.where("name like ?", "%#{params[:key]}%").paginate(:per_page => 20, :page => params[:page])
  end

  private

  def find_model
  	@comic = Comic.find(params[:id]) if params[:id]
  end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController

  before_filter :find_comic

  def show
  end
 

  def search
    @comics1 = Comic.search_by_name_like(params[:key])
    @comic2 = Comic.search_by_tag_name(params[:key])
    @comics = (@comics1 | @comic2).paginate(:page => params[:page], :per_page => 20)
  end

  def hot
    @comics = Comic.hot.paginate(:per_page => 20, :page => params[:page])
  end

  def latest
    @comics = Comic.latest.limit(100).paginate(:per_page => 20, :page => params[:page])
  end



  private

  def find_comic
    @comic = Comic.find(params[:id]) if params[:id]
  end

end

app/helpers/admin/comics_helper.rb
module Admin::ComicsHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/views/admin/comics/_comics.html.erb
<%= content_for :head do %>
    <script type="text/javascript">
        $(function () {
            $('select').change(function () {
                $(this).closest('.edit_comic').submit();
            });
        })
    </script>

    <style type="text/css">
        select {
            width: 80px;
        }

        form {
            display: inline;
        }
    </style>
<% end -%>



<div class='well'>

<table class="table table-striped">
        <thead>
          <tr>
            <th>ID</th>
            <th>名字</th>
            <th>状态</th>
            <th>章节</th>
            <th>热度</th>
            <th>标签</th>
            <th>推荐</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
        	<% @comics.each do |comic| %>
        		<tr>
        		  <td><%= comic.id %></td>
        		  <td><%= link_to comic.name, admin_comic_path(comic), :target => '_blank' %></td>
                  <td>
                    <%= form_for comic, :url => admin_comic_path(comic) do |f| %>
                        <%= f.select :nature, [['未完结', '0'], ['已完结',1]] %>
                    <% end -%>

                  </td>
                  <th><%= comic.sections.size %></th>
        		  <td>
        		  	<%= form_for comic, :url => admin_comic_path(comic) do |f| %>
        		  		<%= f.select :hot, (1..10).to_a.map{|i|[i, i]} %>
        		  	<% end -%>
        		  </td>
                  <td>
                    <%= form_tag add_tag_admin_comic_path(comic) do %>
                        <%= text_field_tag :tags, comic.tags.map{|t|t.name}.join(' '), :size => 7, :style => 'width:100px' %>
                        <button class='btn' type='submit'>更新</button>
                    <% end -%>
                  </td>
                  <td>
                    <%= form_for comic, :url => recommand_admin_comic_path(comic), :method => :post do |f| %>
                        <button class='btn' type='submit'>推荐</button>
                    <% end -%>
                  </td>
        		  <td>
                    <div>
        		  	<% if comic.enable? %>

        		  	<%= form_tag disable_admin_comic_path(comic) do %>
        		  		<button type='submit' class='btn btn-warning disable'>禁用</button>
        		  	<% end -%>
                    <%= form_tag update_section_list_admin_comic_path(comic) do %>
                        <button type='submit' class='btn update'>更新</button>
                    <% end -%>
        		  	<% else %>
        		  	<%= form_tag enable_admin_comic_path(comic) do %>
        		  		<button type='submit' class="btn btn-success enable">启用</button>
        		  	<% end -%>
                    
        		  	<% end -%>
                    </div>
        		  </td>
        		</tr>
        	<% end -%>
        </tbody>
      </table>


 <%= will_paginate @comics, :class => 'pager' %>

 </div>

app/views/admin/comics/enable_list.html.erb
<ul class="nav nav-pills">
  <li   class='active'>
    <a href="/admin/comics/enable_list">enable</a>
  </li>
  <li><a href="/admin/comics/disable_list">disable</a></li>
  <li><a href="/admin/comics">all</a></li>
</ul>

<div class='well'>
	count: <%= Comic.enable.size %>
	<%= form_tag  update_all_sections_admin_comics_path do |f| %>
		<button class='btn'>更新已启用的漫画</button>
	<% end -%>
</div>

<div class='row'>

	

<div class='span10'>

	

	<%= render :partial => 'comics' %>
	     

</div>

</div>

app/views/admin/comics/index.html.erb
	<div>
        <%= form_tag search_admin_comics_path, :class => 'form-search' do %>
            <%= text_field_tag :key , '',:class => 'input-medium search-query' %>
		  <button type="submit" class="btn">搜索</button>
          <% end -%>
	</div>

<ul class="nav nav-pills">
  <li>
    <a href="/admin/comics/enable_list">enable</a>
  </li>
  <li><a href="/admin/comics/disable_list">disable</a></li>
  <li class='active'><a href="/admin/comics">all</a></li>
</ul>

<div class='well'>
	count: <%= Comic.all.size %>
</div>

<div class='row'>

	

<div class='span10'>

	

	<%= render :partial => 'comics' %>
	     

</div>

</div>

app/views/admin/comics/search.html.erb
<div class='row'>

	

<div class='span10'>

	

	<%= render :partial => 'comics' %>
	     

</div>

</div>

app/views/admin/comics/show.html.erb
<%= form_for(@comic, :url => admin_comic_path(@comic) , :html => {:class => 'form-horizontal'}) do |f| %>
  <fieldset>
    <legend><%= @comic.name %></legend>
    <div class="control-group">
    	<%= f.label :name, "名字", :class => 'control-label' %>
      <div class="controls">
      	<%= f.text_field :name, :class => 'input-xlarge' %>
      </div>
    </div>

    <div class="control-group">
    	<%= f.label :description, "简介", :class => 'control-label' %>
      <div class="controls">
      	<%= f.text_area :description, :class => 'input-xlarge', :rows => 5 %>
      </div>
    </div>

    <div class="control-group">
    	<%= f.label :hot, "热度", :class => 'control-label' %>
      <div class="controls">
        <%= f.select :hot, (1..10).to_a.map{|i|[i, i]} %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :nature, "连载状态", :class => 'control-label' %>
      <div class="controls">
        <%= f.select :nature, [['未完结', 0], ['已完结',1]] %>
      </div>
    </div>

    <div class="form-actions">
        <button type="submit" class="btn btn-success">保存</button>
    </div>

  </fieldset>
<% end -%>